// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTI4fk7BXRP3fi40jkqPQ6s3i7KzrW-h0',
    appId: '1:1069485843255:web:1f129051dd59f1a05e30b2',
    messagingSenderId: '1069485843255',
    projectId: 'smart-study-plannen05',
    authDomain: 'smart-study-plannen05.firebaseapp.com',
    storageBucket: 'smart-study-plannen05.firebasestorage.app',
    measurementId: 'G-KM0VDD35L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Pxrv5uKGKfagAI_E83P_nq-W8Jk6rA8',
    appId: '1:1069485843255:android:57210f8bca61090b5e30b2',
    messagingSenderId: '1069485843255',
    projectId: 'smart-study-plannen05',
    storageBucket: 'smart-study-plannen05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxaTL8E1RWGJlaP3_hNJsudXrqnfXeAK4',
    appId: '1:1069485843255:ios:81fb1e7fb7fad5f95e30b2',
    messagingSenderId: '1069485843255',
    projectId: 'smart-study-plannen05',
    storageBucket: 'smart-study-plannen05.firebasestorage.app',
    iosBundleId: 'com.example.smartStudyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxaTL8E1RWGJlaP3_hNJsudXrqnfXeAK4',
    appId: '1:1069485843255:ios:81fb1e7fb7fad5f95e30b2',
    messagingSenderId: '1069485843255',
    projectId: 'smart-study-plannen05',
    storageBucket: 'smart-study-plannen05.firebasestorage.app',
    iosBundleId: 'com.example.smartStudyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTI4fk7BXRP3fi40jkqPQ6s3i7KzrW-h0',
    appId: '1:1069485843255:web:32b99677bbe3322c5e30b2',
    messagingSenderId: '1069485843255',
    projectId: 'smart-study-plannen05',
    authDomain: 'smart-study-plannen05.firebaseapp.com',
    storageBucket: 'smart-study-plannen05.firebasestorage.app',
    measurementId: 'G-E5JHXF5H47',
  );
}
