name: smart_study_planner
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  google_sign_in: ^6.3.0
  table_calendar: ^3.0.9
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/home.png
    - assets/images/calendar.png
    - assets/images/manage.png
    - assets/images/account.png
    - assets/images/bg.png
    - assets/images/percent.png
    - assets/images/succeed.png
    - assets/images/setting.png
    - assets/images/circle.png
    - assets/images/back.png
    - assets/images/next.png
    - assets/images/trash_can.png
    - assets/images/menu2.png
    - assets/images/logo.png
    - assets/images/google.png
    - assets/images/notifications.png
    - assets/images/Send.png
    - assets/images/light.png
    - assets/images/Dark.png
    - assets/images/add1.png
    - assets/images/add2.png
    - assets/images/add3.png
    - assets/images/add4.png
    - assets/images/add5.png
    - assets/images/add6.png
    - assets/images/add7.png
    - assets/images/add8.png
    - assets/images/add9.png
    - assets/images/add10.png
    - assets/images/add11.png
    - assets/images/add12.png
    - assets/images/add13.png
    - assets/images/add14.png
    - assets/images/add15.png
    - assets/images/add16.png
    - assets/images/add17.png
    - assets/images/add18.png
    - assets/images/add19.png
    - assets/images/add20.png
    - assets/images/add21.png
    - assets/images/add22.png
    - assets/images/add23.png
    - assets/images/add24.png
    - assets/images/add25.png
    - assets/images/add26.png
    - assets/images/add27.png
    - assets/images/add28.png
    - assets/images/add29.png
    - assets/images/add30.png
    - assets/images/add31.png
    - assets/images/add32.png
    - assets/images/add33.png
    - assets/images/add34.png
    - assets/images/Avt1.png
    - assets/images/Avt2.png
    - assets/images/Avt3.png
    - assets/images/Avt4.png
    - assets/images/Avt5.png
    - assets/images/Avt6.png
    - assets/images/Avt7.png
    - assets/images/Avt8.png
    - assets/images/Avt9.png
    - assets/images/Avt10.png
    - assets/images/Avt11.png
    - assets/images/Avt12.png
    - assets/images/Avt13.png
    - assets/images/Avt14.png
    - assets/images/Avt15.png
    - assets/images/Avt16.png
    - assets/images/Avt17.png
    - assets/images/Avt18.png
    - assets/images/Avt19.png
    - assets/images/Avt20.png
    - assets/images/Avt21.png
    - assets/images/Avt22.png
    - assets/images/Avt23.png
    - assets/images/Avt24.png
    - assets/images/Avt25.png
    - assets/images/Avt26.png
    - assets/images/Avt27.png
    - assets/images/Avt28.png
    - assets/images/Avt29.png
    - assets/images/Avt30.png
    - assets/images/Avt31.png
    - assets/images/Avt32.png
    - assets/images/Avt33.png
    - assets/images/Avt34.png
    - assets/images/Avt35.png
    - assets/images/IC1.png
    - assets/images/IC2.png
    - assets/images/IC3.png
    - assets/images/IC4.png
    - assets/images/IC5.png
    - assets/images/IC6.png
    - assets/images/IC7.png
    - assets/images/IC8.png
    - assets/images/IC9.png
    - assets/images/IC10.png
    - assets/images/setting2.png
    - assets/images/Send3.png